### ISSUE TITLE
Menu does not work on my android chrome


### ISSUE THREAD

**Issue by LukasWallrich** [forrtproject/forrtproject.github.io#117]
When second level is opened up, first level collapses so that I can never click the links ... See video

https://github.com/forrtproject/forrtproject.github.io/assets/60155545/8da3aa43-e15a-41fb-b444-1a4162592dc6

**Comment by DAKiersz** [comment]
Tagged as a bug. This will be good to put in our accessible audit @bethaniley

**Comment by flavioazevedo** [comment]
A long time ago, when we had just finished the website, I searched for help about this and the instructions were that when using the website we needed to hold the menu we want to open and then the sub-menus don't disappear. It still works on my Android now. However, obviously, this isn't desirable because it add barriers to the website! I just thought it would be good to mention it (perhaps there is an internal option that removes this need to hold a menu or a configuration that changes the default).

**Comment by LukasWallrich** [comment]
Fixed in PR #180
